name: jga_baby_app
description: "JGA Tamagotchi für den Bräutigam."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  sensors_plus: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/weed.png
    - assets/grinder_top.png
    - assets/grinder_side.png
    - assets/joint_unlit.png
    - assets/joint_lit.png
    - assets/family_boro.png # NEU
    - assets/baby.png        # NEU