name: jga_baby_app
description: "JGA Tamagotchi für den Bräutigam."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  sensors_plus: ^6.1.1
  shared_preferences: ^2.2.2
  alarm: ^4.1.1
  flutter_local_notifications: ^17.0.0 # NEU hinzugefügt

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/weed.png
    - assets/grinder_top.png
    - assets/grinder_side.png
    - assets/joint_unlit.png
    - assets/joint_lit.png
    - assets/family_boro.png
    - assets/baby.png
    - assets/profil_picture.jpg
    - assets/keyboard.jpg
    - assets/grinder_base_open.png
    - assets/joint_mini_game_background.png
    - assets/weed_leaf.png
    - assets/crying.mp3
    - assets/gin_baby_bottle.png
    - assets/gin_baby_bottle_background.png